language: node_js
node_js:
  - "4"
  - "6"
before_script:
  - yarn global add gulp
cache:
  yarn: true
  directories:
    - node_modules
script:
  gulp test
after_success:
  - chmod a+x deploy.sh
  - ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "5e22eff332c7"
  - COMMIT_AUTHOR_EMAIL: "m2-boilerplate@hampe.co"
